### ISSUE TITLE
Unable to get electron titlebar working

### ISSUE THREAD

**Issue by matt3224** [Menci/electron-titlebar#1]
Hey,

I have added the package and required it however i get the following

```
Uncaught Exception:
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/Matt/Sites/rightlance-electro/node_modules/electron-titlebar/index.js:149:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at App.createWindow (/Users/Matt/Sites/rightlance-electro/main.js:32:5)
    at emitTwo (events.js:111:20)
```

**Comment by Menci** [comment]
Are you requiring it in the main process? You should use it in the **renderer** process.

**Comment by Menci** [comment]
Are you requiring it in the main process? You should use it in the **renderer process**.

I also noticed that you are under OS X or macOS. electron-titlebar is mainly for Windows and Linux, but you can test it under your platform. Just set the BrowserWindow option `frame: false` and see https://github.com/Menci/electron-titlebar#platform

**Comment by matt3224** [comment]
thanks
