### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ludovc** [Menci/electron-titlebar#11]
When I try to run my application, I get this error:

App threw an error during load
ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\USER\code\APP\node_modules\electron-titlebar\index.js:149:1)
    at Object.<anonymous> (C:\Users\USER\code\APP\node_modules\electron-titlebar\index.js:152:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\USER\code\APP\main.js:2:1)

**Comment by ludovc** [comment]
Ok, I guess I got it.

I added `require('electron-titlebar')` in the main process, but DOM cannot be accessed in the main process.

So I've added that in the renderer process.
