### ISSUE TITLE
Requiring electron-titlebar 

### ISSUE THREAD

**Issue by samuelmodlin** [Menci/electron-titlebar#2]
I encountered this error when requiring this module in my main process. New to Node/Electron so I apologize if I am missing something obvious. 

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/Sam/NotesApp/node_modules/electron-titlebar/index.js:149:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Sam/NotesApp/main.js:9:1)
    at Module._compile (module.js:556:32)

**Comment by Menci** [comment]
See #1.
